### ISSUE TITLE
Nlog.Config dependency

### ISSUE THREAD

**Issue by DonMcNamara** [Iristyle/NLog.AirBrake#14]
I'm not so sure that nlog.config should be listed as a dependency. Thoughts?

**Comment by Iristyle** [comment]
I added it because you were using it in packages.config for the TestApp.

https://github.com/EastPoint/NLog.AirBrake/blob/master/src/NLog.AirBrake.TestApp/packages.config#L4

I suppose you are technically right that it's not a requirement though.  We should probably add to the example in the README for how to use code to do the config.

**Comment by DonMcNamara** [comment]
Closed with pull request 18
